services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: lead-backend-dev
    restart: always
    ports:
      - "4000:4000"
      - "9229:9229"  # Puerto para depuración de Node.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://admin_lead:LeadPass2024@mongodb:27017/lead-db-prueba?authSource=admin
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:4000
      - S3_ENDPOINT=https://sfo3.digitaloceanspaces.com
      - BUCKET_NAME=lead-spaces
      - SPACESHOST=https://lead-spaces.sfo3.digitaloceanspaces.com/
      - AWS_ACCESS_KEY_ID=R26X7JJS3B7PTESEAUKG
      - AWS_SECRET_ACCESS_KEY=poW5uZHFYxxcfkmvOEcHrDwsciUErYHyyejsBfsx+mI
      - SESSION_SECRET=lead-dev-session-secret-2024
      - SECRET=lead-dev-secret-2024
      - LOG_LEVEL=debug
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=lead-db-prueba
      - MONGODB_USERNAME=admin_lead
      - MONGODB_PASSWORD=LeadPass2024
      - MONGODB_AUTH_SOURCE=admin
      - VAPID_PUBLIC_KEY=BH8QuI-t1TieUaywkDJs7MhTLYVj6ouwOfM8NZjXv_S1QgX78HmLJQL2MEp9Zm6mCsPrzYnagrG299uCFN8d5dI
      - VAPID_PRIVATE_KEY=LTyPAFQGI7wPaci3Fttt-zod9H8voNMfLaJwFKN8JMg
      - VAPID_SUBJECT=mailto:admin@lead-inmobiliaria.com
      - FCM_SERVER_KEY=YOUR_FCM_SERVER_KEY_HERE
    user: "node"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # Removido read_only: true para permitir logs y archivos temporales
    tmpfs:
      - /tmp
      - /usr/src/app/logs
    command: npx nodemon --inspect=0.0.0.0:9229 --legacy-watch src/index.js
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - lead-network-dev
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: lead-frontend-dev
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/usr/src/app:delegated
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
      - VITE_VAPID_PUBLIC_KEY=BH8QuI-t1TieUaywkDJs7MhTLYVj6ouwOfM8NZjXv_S1QgX78HmLJQL2MEp9Zm6mCsPrzYnagrG299uCFN8d5dI
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - lead-network-dev

  mongodb:
    image: mongo:8.0
    container_name: lead-mongodb-dev
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_dev:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      - MONGODB_INITDB_DATABASE=lead-db-prueba
      - MONGODB_INITDB_ROOT_USERNAME=admin_lead
      - MONGODB_INITDB_ROOT_PASSWORD=LeadPass2024
    command: mongod --bind_ip_all --auth
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    networks:
      - lead-network-dev
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "mongosh", "--username", "admin_lead", "--password", "LeadPass2024", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  lead-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev: 