version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: lead-backend-dev
    restart: always
    ports:
      - "4000:4000"
      - "9229:9229"  # Puerto para depuración de Node.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://admin_lead:LeadPass2024@mongodb:27017/lead-db-prueba?authSource=admin
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:4000
      - S3_ENDPOINT=https://sfo3.digitaloceanspaces.com
      - BUCKET_NAME=lead-spaces
      - SPACESHOST=https://lead-spaces.sfo3.digitaloceanspaces.com/
      - AWS_ACCESS_KEY_ID=R26X7JJS3B7PTESEAUKG
      - AWS_SECRET_ACCESS_KEY=poW5uZHFYxxcfkmvOEcHrDwsciUErYHyyejsBfsx+mI
    user: "node"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    command: nodemon --legacy-watch src/index.js
    depends_on:
      - mongodb
    networks:
      - lead-network-dev
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: lead-frontend-dev
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/usr/src/app:delegated
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - lead-network-dev

  mongodb:
    image: mongo:latest
    container_name: lead-mongodb-dev
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_dev:/data/db
      - .:/dump
    environment:
      - MONGODB_INITDB_DATABASE=lead-db-prueba
      - MONGODB_INITDB_ROOT_USERNAME=admin_lead
      - MONGODB_INITDB_ROOT_PASSWORD=LeadPass2024
    command: mongod --bind_ip_all --auth --tlsMode disabled
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - lead-network-dev
    security_opt:
      - no-new-privileges:true

networks:
  lead-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev: 