FROM node:18

WORKDIR /usr/src/app

# Copiamos los archivos de dependencias
COPY package*.json ./

# Instalamos solo las dependencias de producción
RUN npm install --production

# Copiamos el resto de archivos del proyecto
COPY . .

# Creamos el directorio Frontend/dist si no existe para evitar errores
RUN mkdir -p Frontend/dist

# Exponemos el puerto que utiliza la aplicación
EXPOSE 4000

# Comando para iniciar la aplicación en modo producción
CMD ["npm", "start"] 