version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: lead-backend-prod
    restart: always
    ports:
      - "127.0.0.1:14000:4000"
    environment:
      - NODE_ENV=production
      - SECRET=erhgvbhbsfedbehbfd
      - PORT=4000
      - MONGODB_URI=mongodb://admin_lead:LeadPass2024@mongodb:27017/lead-db-prod?authSource=admin
      - ALLOWED_ORIGINS=https://lead-inmobiliaria.com:4000
      - BUCKET_NAME=lead-spaces
      - AWS_ACCESS_KEY_ID=R26X7JJS3B7PTESEAUKG
      - AWS_SECRET_ACCESS_KEY=poW5uZHFYxxcfkmvOEcHrDwsciUErYHyyejsBfsx+mI
      - S3_ENDPOINT=sfo3.digitaloceanspaces.com
      - USE_S3=true
    volumes:
      - ./Frontend/dist:/usr/src/app/Frontend/dist:ro
      - frontend_node_modules:/usr/src/app/Frontend/node_modules
    user: "node"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: false
    tmpfs:
      - /tmp
    depends_on:
      - mongodb
    networks:
      - lead-network-prod
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: lead-mongodb-prod
    restart: always
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongodb_data_prod:/data/db
      - .:/dump:ro
    environment:
      - MONGODB_INITDB_DATABASE=lead-db-prod
      - MONGODB_INITDB_ROOT_USERNAME=admin_lead
      - MONGODB_INITDB_ROOT_PASSWORD=LeadPass2024
    command: mongod --bind_ip_all --auth --tlsMode disabled
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - lead-network-prod
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  lead-network-prod:
    driver: bridge

volumes:
  mongodb_data_prod:
  frontend_node_modules: