version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: lead-backend-dev
    restart: always
    ports:
      - "4000:4000"
      - "9229:9229"  # Puerto para depuración de Node.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/lead-db-prueba
    user: "node"
    security_opt:
      - no-new-privileges:true
    command: nodemon --legacy-watch src/index.js
    depends_on:
      - mongodb
    networks:
      - lead-network-dev

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: lead-frontend-dev
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/usr/src/app:delegated
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - lead-network-dev

  mongodb:
    image: mongo:latest
    container_name: lead-mongodb-dev
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_dev:/data/db
      - .:/dump
    environment:
      - MONGODB_INITDB_DATABASE=lead-db-prueba
    command: mongod --bind_ip_all
    networks:
      - lead-network-dev

networks:
  lead-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev: 