version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: lead-backend-prod
    restart: always
    ports:
      - "127.0.0.1:14000:4000"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - PORT=4000
      - LOG_LEVEL=info
      # Orígenes permitidos (usar .env.prod por defecto, aquí como respaldo)
      - ALLOWED_ORIGINS=https://lead-inmobiliaria.com,https://www.lead-inmobiliaria.com
      # VAPID Keys para Push Notifications
      - VAPID_PUBLIC_KEY=BH8QuI-t1TieUaywkDJs7MhTLYVj6ouwOfM8NZjXv_S1QgX78HmLJQL2MEp9Zm6mCsPrzYnagrG299uCFN8d5dI
      - VAPID_PRIVATE_KEY=LTyPAFQGI7wPaci3Fttt-zod9H8voNMfLaJwFKN8JMg
      - VAPID_SUBJECT=mailto:zaidnevarez7@gmail.com
    volumes:
      - ./Frontend/dist:/usr/src/app/Frontend/dist:ro
      - ./FrontendPublic:/usr/src/app/FrontendPublic:ro
      - frontend_node_modules:/usr/src/app/Frontend/node_modules
      - uploads:/usr/src/app/src/public/uploads
    user: "nodejs"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: false
    tmpfs:
      - /tmp
      - /usr/src/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - lead-network-prod
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '0.90'
        reservations:
          memory: 1G
          cpus: '0.50'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:8.0
    container_name: lead-mongodb-prod
    restart: always
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongodb_data_prod:/data/db
      - ./init-mongo-prod.sh:/docker-entrypoint-initdb.d/init-mongo-prod.sh:ro
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin_lead
      - MONGODB_INITDB_ROOT_PASSWORD=LeadPass2024
      - MONGODB_INITDB_DATABASE=lead-db-prod
    command: mongod --bind_ip_all --auth
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          memory: 1G
          cpus: '1'
    networks:
      - lead-network-prod
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "mongosh", "--username", "admin_lead", "--password", "LeadPass2024", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  lead-network-prod:
    driver: bridge

volumes:
  mongodb_data_prod:
  frontend_node_modules:
  uploads: