export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/UsersTable";
export * from "@/pages/dashboard/ProfileUsers";
export * from "@/pages/dashboard/EmpleadosTable";
export * from "@/pages/dashboard/ProfileEmpleados";
export * from "@/pages/dashboard/EditarNomina";
export * from "@/pages/dashboard/DocumentosEmpleado";
export * from "./CrearEmpleado";
export * from "./EditarEmpleado";
export { CrearNomina } from "@/pages/dashboard/CrearNomina";
