export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/Users/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/Users/UsersTable";
export * from "@/pages/dashboard/Users/ProfileUsers";
export * from "@/pages/dashboard/Empleados/EmpleadosTable";
export * from "@/pages/dashboard/Empleados/ProfileEmpleados";
export * from "@/pages/dashboard/Empleados/EditarNomina";
export * from "@/pages/dashboard/Empleados/DocumentosEmpleado";
export * from "@/pages/dashboard/Empleados/CrearEmpleado";
export * from "@/pages/dashboard/Empleados/EditarEmpleado";
export { CrearNomina } from "@/pages/dashboard/Empleados/CrearNomina";
export * from "@/pages/dashboard/Publicidad";
